name: Hadoop Playground
safe: true
lsi: false
pygments: true
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
path: http://mbartling.github.io/Hadoop_playground 
baseurl: /Hadoop_playground
